Rails.application.routes.draw do

  get "login" => "users#login_form"
  post "login"=>"application#login"
  post "users/scoreupdate" => "users#scoreupdate"
  get "users/scoreedit" => "users#scoreedit"
  post "users/:id/update" => "users#update"
  get "users/:id/edit" => "users#edit"
  post "users/create" => "application#create"
  get "users/new"   => "users#new"
  get 'users/edit'=>"users#edit"
  get "users/:id" => "users#show"
  get "/"=>"home#top"
  get "workbooks/index" => "workbooks#index"

  get "rankings/rank900" => "rankings#rank900"
  get "rankings/rank800" => "rankings#rank800"
  get "rankings/rank700" => "rankings#rank700"
  get "rankings/rank600" => "rankings#rank600"
  get "rankings/rank500" => "rankings#rank500"
  get "rankings/rank400" => "rankings#rank400"
  get "rankings/rank300" => "rankings#rank300"
  get "rankings/rank200" => "rankings#rank200"
  get "rankings/listening" => "rankings#listening"
  get "rankings/reading" => "rankings#reading"
  get "rankings/all" => "rankings#all"
  get "rankings/word" => "rankings#word"
  get "rankings/grammer" => "rankings#grammer"
  get "rankings/workbook" => "rankings#workbook"
  get "rankings/satisfaction" => "rankings#satisfaction"
  get "rankings/costpeformance" => "rankings#costpeformance"
  get "rankings/detail" => "rankings#detail"
  get "rankings/paper" => "rankings#paper"
  get "rankings/app" => "rankings#app"


  post "workbooks/:workbook_id/post_create" => "workbooks#post_create"
  get "workbooks/:workbook_id/post" => "workbooks#post"
  get "workbooks/:workbook_id" => "workbooks#show"
  post "logout" => "application#logout"
  post "likes/:post_id/create" => "likes#post_like_create"
  post "likes/:id/creates" => "likes#user_like_create"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
