class HomeController < ApplicationController
  def top
    @workbook=Workbook.find_by(id:1)
    @workbook900=Workbook.joins(:posts).where("points >= 900 AND points <= 990").select('workbooks.id,workbooks.image,workbooks.product,workbooks.author,count(posts.id) as posts_count,avg(satisfaction) as satisfaction_all').group(:id).order('posts_count desc').first
    @workbook800=Workbook.joins(:posts).where("points >= 800 AND points <= 895").select('workbooks.id,workbooks.image,workbooks.product,workbooks.author,count(posts.id) as posts_count,avg(satisfaction) as satisfaction_all').group(:id).order('posts_count desc').first
    @workbook700=Workbook.joins(:posts).where("points >= 700 AND points <= 795").select('workbooks.id,workbooks.image,workbooks.product,workbooks.author,count(posts.id) as posts_count,avg(satisfaction) as satisfaction_all').group(:id).order('posts_count desc').first
    @workbook600=Workbook.joins(:posts).where("points >= 600 AND points <= 695").select('workbooks.id,workbooks.image,workbooks.product,workbooks.author,count(posts.id) as posts_count,avg(satisfaction) as satisfaction_all').group(:id).order('posts_count desc').first
    @workbook500=Workbook.joins(:posts).where("points >= 500 AND points <= 595").select('workbooks.id,workbooks.image,workbooks.product,workbooks.author,count(posts.id) as posts_count,avg(satisfaction) as satisfaction_all').group(:id).order('posts_count desc').first
    @workbook400=Workbook.joins(:posts).where("points >= 400 AND points <= 495").select('workbooks.id,workbooks.image,workbooks.product,workbooks.author,count(posts.id) as posts_count,avg(satisfaction) as satisfaction_all').group(:id).order('posts_count desc').first
    @workbook300=Workbook.joins(:posts).where("points >= 300 AND points <= 395").select('workbooks.id,workbooks.image,workbooks.product,workbooks.author,count(posts.id) as posts_count,avg(satisfaction) as satisfaction_all').group(:id).order('posts_count desc').first
    @workbook200=Workbook.joins(:posts).where("points >= 200 AND points <= 295").select('workbooks.id,workbooks.image,workbooks.product,workbooks.author,count(posts.id) as posts_count,avg(satisfaction) as satisfaction_all').group(:id).order('posts_count desc').first
    @workbook_book=Workbook.joins(:posts).select('workbooks.id,workbooks.image,workbooks.product,workbooks.author,count(posts.id) as posts_count,avg(satisfaction) as satisfaction_all').group(:id).order('posts_count desc').first
    @workbook_all=Workbook.where(all: 1).joins(:posts).select('workbooks.id,workbooks.image,workbooks.product,workbooks.author,count(posts.id) as posts_count,avg(satisfaction) as satisfaction_all').group(:id).order('posts_count desc').first
    @workbook_listening=Workbook.where(listening: 1).joins(:posts).select('workbooks.id,workbooks.image,workbooks.product,workbooks.author,count(posts.id) as posts_count,avg(satisfaction) as satisfaction_all').group(:id).order('posts_count desc').first
    @workbook_reading=Workbook.where(reading: 1).joins(:posts).select('workbooks.id,workbooks.image,workbooks.product,workbooks.author,count(posts.id) as posts_count,avg(satisfaction) as satisfaction_all').group(:id).order('posts_count desc').first
    @workbook_grammer=Workbook.where(grammer: 1).joins(:posts).select('workbooks.id,workbooks.image,workbooks.product,workbooks.author,count(posts.id) as posts_count,avg(satisfaction) as satisfaction_all').group(:id).order('posts_count desc').first
    @workbook_word=Workbook.where(word: 1).joins(:posts).where("points >= 200 AND points <= 295").select('workbooks.id,workbooks.image,workbooks.product,workbooks.author,count(posts.id) as posts_count,avg(satisfaction) as satisfaction_all').group(:id).order('posts_count desc').first
    @workbook200=Workbook.joins(:posts).where("points >= 200 AND points <= 295").select('workbooks.id,workbooks.image,workbooks.product,workbooks.author,count(posts.id) as posts_count,avg(satisfaction) as satisfaction_all').group(:id).order('posts_count desc').first
    @workbook_detail=Workbook.joins(:posts).select('workbooks.id,workbooks.image,workbooks.product,workbooks.author,count(posts.id) as posts_count,avg(detail) as satisfaction_all').group(:id).order('satisfaction_all desc').first
    @workbook_ease=Workbook.joins(:posts).select('workbooks.id,workbooks.image,workbooks.product,workbooks.author,count(posts.id) as posts_count,avg(ease) as satisfaction_all').group(:id).order('satisfaction_all desc').first
    @workbook_cost=Workbook.joins(:posts).select('workbooks.id,workbooks.image,workbooks.product,workbooks.author,count(posts.id) as posts_count,avg(volume) as satisfaction_all').group(:id).order('satisfaction_all desc').first
  end
end
